import {ColumnIfc, TableColumns, TableColumn} from 'NG2TableView';

export const PageTableColumns: Array<ColumnIfc> = new TableColumns()
  .addCol(new TableColumn()
    .setTitle('ID')
    .setName('id')
    .setSort(true)
  )
  .addCol(new TableColumn()
    .setTitle('Name')
    .setName('contactName')
    .setSort(true)
  )
  .addCol(new TableColumn()
    .setTitle('Company')
    .setName('name')
    .setSort(true)
  )
  .addCol(new TableColumn()
    .setTitle('Supervisor')
    .setName('supervisor')
    .setSort(true)
  )
  .addCol(new TableColumn()
    .setTitle('Project Title')
    .setName('title')
  )
  // .addCol(new TableColumn()
  //   .setTitle('Email')
  //   .setName('contactEmail')
  // )
  .addCol(new TableColumn()
    .setTitle('Status')
    .setName('status')
    .setSort(true)
  )
  .getCols();

console.log('Forbindelse til column-factory' + PageTableColumns);


